package com.gabrielhamartins.backend_challenge.util;

public class TestUtil {

    public static final String API_V1_BASE_URL = "/backend-challenge/v1";
    public static final String VALID_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJTZWVkIjoiNzg0MSIsIk5hbWUiOiJUb25pbmhvIEFyYXVqbyJ9.QY05sIjtrcJnP533kQNk8QXcaleJ1Q01jWY_ZzIZuAg";
    public static final String INVALID_TOKEN_FORMAT = "eyJhbGciOiJzI1NiJ9.dfsdfsfryJSr2xrIjoiQWRtaW4iLCJTZrkIjoiNzg0MSIsIk5hbrUiOiJUb25pbmhvIEFyYXVqbyJ9.QY05fsdfsIjtrcJnP533kQNk8QXcaleJ1Q01jWY_ZzIZuAg";
    public static final String INVALID_TOKEN_CLAIM_NAME_WITH_DIGITS = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiRXh0ZXJuYWwiLCJTZWVkIjoiODgwMzciLCJOYW1lIjoiTTRyaWEgT2xpdmlhIn0.6YD73XWZYQSSMDf6H0i3-kylz1-TY_Yt6h1cV2Ku-Qs";
    public static final String INVALID_TOKEN_CLAIMS_SIZE = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiTWVtYmVyIiwiT3JnIjoiQlIiLCJTZWVkIjoiMTQ2MjciLCJOYW1lIjoiVmFsZGlyIEFyYW5oYSJ9.cmrXV_Flm5mfdpfNUVopY_I2zeJUy4EZ4i3Fea98zvY";
    public static final String INVALID_TOKEN_CLAIM_SEED_NOT_PRIME = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJTZWVkIjoiMTAiLCJOYW1lIjoiVG9uaW5obyBBcmF1am8ifQ.wMQO8f_RTE6AdwVfUk4fs5mEz7SPUXr1g-Oj6U_ehtQ";
    public static final String INVALID_TOKEN_CLAIMS = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJTZWVlZCI6Ijc4NDEiLCJOYW1lIjoiVG9uaW5obyBBcmF1am8ifQ.OGsVjJK3t-0MLRusVn8cYrOkVNDpAgxijhnVkinP19A";
    public static final String INVALID_TOKEN_CLAIM_NAME_SIZE = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJTZWVkIjoiNzg0MSIsIk5hbWUiOiJUb25pbmhvIEFyYXVqbyBkeWFzZ2R5dXNhZ2R1eWFzZ2R5dWFzZ2R5dWFzZ2R5dWFzZ2R1YXlzZ2R5dWFzZ2R5dWFzZGdhc3l1ZGd5YXN1ZGdzdWFkZ3N1YWRndWFzZGd5YXN1ZGd5YXN1ZGd5dWFzZGd5YXVzZGd5YXN1ZGd1YXlzZGdzYXV1dXV1dXV1dXV1dXV1dXV1eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eWdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWEifQ.3dYSRut0sDV8virWiU5fk3J3kkGDLpUtXuuq98aMIv4";
    public static final String INVALID_TOKEN_CLAIM_ROLE = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW5pc3RyYWRvciIsIlNlZWQiOiI3ODQxIiwiTmFtZSI6IlRvbmluaG8gQXJhdWpvIn0.ZEGpL1sA6P9LNKFsnBPAVT7mzCIPvSXt8gxAbwjvrCY";

}
